### ISSUE TITLE
Publish on Spotify?

### ISSUE THREAD

**Issue by sockeqwe** [artem-zinnatullin/TheContext-Podcast#107]
Seems like Spotify opened tge door for everyone to publish podcast on spitify https://podcasters.spotify.com

What do you think? We already published on google play music and Spotify seems to publish a standalone app for android wear soon (November) which I would love to use for  listening to podcast while jogging  ;)

**Comment by artem-zinnatullin** [comment]
Yep, we should try that! I've added it to my todo, will report progress here

**Comment by sockeqwe** [comment]
Well I can also do it. Looks pretty straight forward. So let me know if you have time to do that, otherwise I can do it ...

**Comment by artem-zinnatullin** [comment]
Actually, I'd prefer you to do it so that we'd own different pieces of distribution

**Comment by sockeqwe** [comment]
Done

![Uploading Screenshot_20181021-064025.png…]()

**Comment by aimanbaharum** [comment]
How do I search this on Spotify?

**Comment by fjoshuajr** [comment]
Here's the link: https://open.spotify.com/show/0IHfgLttmSoijo2XIRM2dq

**Comment by aimanbaharum** [comment]
> Here's the link: https://open.spotify.com/show/0IHfgLttmSoijo2XIRM2dq

Link somehow doesn't redirect me to Spotify. Found it by searching **#androiddev** instead. 😃

**Comment by fjoshuajr** [comment]
> > Here's the link: [open.spotify.com/show/0IHfgLttmSoijo2XIRM2dq](https://open.spotify.com/show/0IHfgLttmSoijo2XIRM2dq)
> 
> Thanks but the link somehow doesn't redirect me to Spotify. Found it by searching **#androiddev** instead.

Hm, a bit odd, would you mind sharing the link from your Spotify? Nevertheless, glad you found it. :wink:
