### ISSUE TITLE
Interested in participating in a "How it's made" interview - Babylon Health

### ISSUE THREAD

**Issue by athkalia** [artem-zinnatullin/TheContext-Podcast#122]
Hello,

I am the engineering manager for the Babylon Health application on Android (https://www.babylonhealth.com) and I am up for having a chat with you guys if you are up for it as well, with regards to how we do things here at Babylon! It's a rather big team of 20 Android engineers, which we are looking to grow to about 30 within the next year. I am sure we'll have plenty to talk about :) 

Please let me know if this is of interest to you.

Thanks,
Sakis

**Comment by sockeqwe** [comment]
Hi Sakis,
that sounds great, thank you for contacting us! What's the best way to
reach out to you?

Sakis Kaliakoudas <notifications@github.com> schrieb am Sa., 18. Mai 2019,
18:44:

**Comment by athkalia** [comment]
My email is sakis.kaliakoudas@babylonhealth.com. Please drop me an email and we'll figure out the rest!

Thanks!

**Comment by sockeqwe** [comment]
Sorry @athkalia  that it took soooooo long to get this published. Here is the PR #124 to publish it. 
Again, I appologize for not having enough time / prioritize this higher to publish this sooner. 

Thank you again for participating. It was a lot of fun and I think its a great episode!

**Comment by athkalia** [comment]
Merry Christmas Hannes! Thanks for taking the time to finalize it 😃 It was definitely good fun!
