### ISSUE TITLE
Suggestions for Episode 2

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/TheContext-Podcast#15]
Main planned theme is **Testing** (yay).

Feel free to suggest themes or questions to discuss or just ideas to improve the podcast. You can also suggest kind of "news" but not sure I want to make a news show, so, yeah :cat: 

Please notice that we can't record 3 hours episodes so some of the suggested themes may be discussed in next episodes.

Thanks!

**Comment by Gi-lo** [comment]
**You could talk about**:
* TDD vs BDD
* Type of tests (Unit, UI, Integration, Regression)
* Mocking and Stubbing (e.g. for network requests)
* Available frameworks (Robolectric, Spock, AssertJ, RxPresso)
* Test Coverage (And why 100% should not be your goal)
* Ways to make your code testable (Separate logic from view, Dependency Injection)
* What to test and what not to test.

Also personally  I would love to know more about https://jetbrains.github.io/spek/docs.html and testing with Kotlin at all.

**Comment by artem-zinnatullin** [comment]
@Gi-lo most of the things were already in the list, but thanks a lot, added some from your list!

**Comment by artem-zinnatullin** [comment]
@Gi-lo just wanted to say that 

>TDD vs BDD

Is not correct comparison :)

**Comment by Gi-lo** [comment]
Yeah you can actually do both ;) It's more like: TDD and BDD

**Comment by b1uebyte** [comment]
— Should QAs write some kind of tests? Or that exclusively developer's concern?
— Why do we want simulator? Is there any perspectives on that field?
— How to organize workflow in team to do better testing?

**Comment by artem-zinnatullin** [comment]
@b1uebyte great questions, added to the list, thanks!

**Comment by DeychAI** [comment]
What should we do to make 1000+ lines activity testable?

**Comment by artem-zinnatullin** [comment]
@DeychAI great question, added to the list!

**Comment by sockeqwe** [comment]
I would love to hear your and your guests opinion on if it makes sense to write unit tests and functional  UI "integration" tests (i.e. with espresso and only mocking the backend) or should we only write functional UI tests since they will test the underlying layers as well. Does testing the underlying layers again with single unit test for each layer / class make sense (testing underlying layers twice)?

**Comment by artem-zinnatullin** [comment]
@sockeqwe got it, will definitely discuss that, thanks!
