### ISSUE TITLE
Use lower bitrate audio files

### ISSUE THREAD

**Issue by jasonwyatt** [artem-zinnatullin/TheContext-Podcast#43]
First off: I'm loving the podcast! Thanks for doing it.

I notice the file sizes for the episodes are a lot larger than they need to be.  An hour of conversation doesn't need to be 60 megs.

**Comment by artem-zinnatullin** [comment]
Got it, ok will try to change it and see if it affects the quality! 

Thank you for feedback Jason, it means a lot for us 💌

**Comment by jasonwyatt** [comment]
It looks like you're using MP3 192, you may want to try MP3 128 or even 96. Speech is much more forgiving than music, typically.

**Comment by artem-zinnatullin** [comment]
Episode 5 is 128 kb/s, 47mb!
