### ISSUE TITLE
Put show notes in the <description> tag for each episode?

### ISSUE THREAD

**Issue by aaronhe42** [artem-zinnatullin/TheContext-Podcast#6]
In the rss feed, the [\<description\>](https://github.com/artem-zinnatullin/TheContext-Podcast/blob/master/feed.rss#L28) tag only contains a brife description of what's the episode like. But it's much more convenient to put show notes inside the tag, so I can open those links while I am listening to the podcast. Just like [Fragmented Podcast](http://fragmentedpodcast.com/feed/).

**Comment by artem-zinnatullin** [comment]
Yeah, definitely needs to be done, have to figure out how to sync it with
md file.

On Fri, 5 Feb 2016, 22:13 Aaron He <notifications@github.com> wrote:

> In the rss feed, the <description>
> <https://githubcom/artem-zinnatullin/TheContext-Podcast/blob/master/feedrss#L28>
> tag only contains a brife description of what's the episode like But it's
> much more convenient to put show notes inside the tag, so I can open those
> links while I am listening to the podcast Just like Fragmented Podcast
> <http://fragmentedpodcastcom/feed/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/TheContext-Podcast/issues/6>.
>
-- 

@artem_zin
