### ISSUE TITLE
Consider using lower bitrate (128 kBit/s)

### ISSUE THREAD

**Issue by sockeqwe** [artem-zinnatullin/TheContext-Podcast#70]
I think 128  kBit/s bitrate  is enough for voice recording like a podcast. This will also save some bandwidth for both, our server and listeners.

I.e. episode 10 is 103 Mb with 128 kBit/s .... With 128 kBit/s would be something between 60 - 75 MB.
Not sure if we should reupload Episode 10 but at least in the future we should consider using lower .bitrate.

What do you think?

**Comment by artem-zinnatullin** [comment]
I'd prefer to keep better bitrate, it's 2017 :) But okay, Episode 11 is 56mb!
